import { ResumeData } from '../types';
import { generateId } from './helpers';

export const initialResumeData: ResumeData = {
  personalInfo: {
    firstName: '',
    lastName: '',
    title: '',
    email: '',
    phone: '',
    location: '',
    website: '',
    linkedin: '',
    github: '',
  },
  summary: '',
  experience: [
    {
      id: generateId(),
      company: '',
      position: '',
      location: '',
      startDate: '',
      endDate: '',
      current: false,
      description: '',
      achievements: [''],
    },
  ],
  education: [
    {
      id: generateId(),
      institution: '',
      degree: '',
      field: '',
      location: '',
      startDate: '',
      endDate: '',
      current: false,
      description: '',
      gpa: '',
    },
  ],
  skills: [
    {
      id: generateId(),
      name: '',
      level: 3,
      category: 'Technical',
    },
  ],
  languages: [],
  certifications: [],
  projects: [],
  interests: [],
};

export const sampleResumeData: ResumeData = {
  personalInfo: {
    firstName: 'Alex',
    lastName: 'Morgan',
    title: 'Senior Software Engineer',
    email: 'alex.morgan@example.com',
    phone: '(555) 123-4567',
    location: 'San Francisco, CA',
    website: 'alexmorgan.dev',
    linkedin: 'linkedin.com/in/alexmorgan',
    github: 'github.com/alexmorgan',
  },
  summary: 'Experienced software engineer with 8+ years specializing in full-stack development. Proficient in React, Node.js, and cloud technologies. Passionate about creating scalable solutions and mentoring junior developers.',
  experience: [
    {
      id: generateId(),
      company: 'TechCorp Inc.',
      position: 'Senior Software Engineer',
      location: 'San Francisco, CA',
      startDate: '2020-03',
      endDate: '',
      current: true,
      description: 'Lead developer for the company\'s flagship product, managing a team of 5 engineers.',
      achievements: [
        'Redesigned authentication system reducing login failures by 45%',
        'Implemented CI/CD pipeline resulting in 3x faster deployment cycles',
        'Led migration from monolith to microservices architecture',
        'Mentored 4 junior developers who were promoted within a year',
      ],
    },
    {
      id: generateId(),
      company: 'DataSystems LLC',
      position: 'Software Engineer',
      location: 'Seattle, WA',
      startDate: '2017-06',
      endDate: '2020-02',
      current: false,
      description: 'Full-stack developer for customer-facing web applications.',
      achievements: [
        'Developed RESTful APIs that improved data retrieval speed by 35%',
        'Created responsive UI components using React and Material UI',
        'Optimized database queries resulting in 50% faster page loads',
        'Implemented automated testing increasing code coverage to 85%',
      ],
    },
  ],
  education: [
    {
      id: generateId(),
      institution: 'University of California, Berkeley',
      degree: 'Master of Science',
      field: 'Computer Science',
      location: 'Berkeley, CA',
      startDate: '2015-08',
      endDate: '2017-05',
      current: false,
      description: 'Specialization in Artificial Intelligence and Machine Learning',
      gpa: '3.85',
    },
    {
      id: generateId(),
      institution: 'Stanford University',
      degree: 'Bachelor of Science',
      field: 'Computer Science',
      location: 'Stanford, CA',
      startDate: '2011-09',
      endDate: '2015-06',
      current: false,
      description: 'Minor in Mathematics',
      gpa: '3.7',
    },
  ],
  skills: [
    {
      id: generateId(),
      name: 'JavaScript',
      level: 5,
      category: 'Programming Languages',
    },
    {
      id: generateId(),
      name: 'React',
      level: 5,
      category: 'Frontend',
    },
    {
      id: generateId(),
      name: 'Node.js',
      level: 4,
      category: 'Backend',
    },
    {
      id: generateId(),
      name: 'AWS',
      level: 4,
      category: 'Cloud',
    },
    {
      id: generateId(),
      name: 'Python',
      level: 3,
      category: 'Programming Languages',
    },
    {
      id: generateId(),
      name: 'Docker',
      level: 4,
      category: 'DevOps',
    },
  ],
  languages: [
    { name: 'English', proficiency: 'Native' },
    { name: 'Spanish', proficiency: 'Professional' },
  ],
  certifications: [
    { name: 'AWS Certified Solutions Architect', issuer: 'Amazon Web Services', date: '2022-05', url: 'credential.net/aws-certificate' },
    { name: 'Professional Scrum Master I', issuer: 'Scrum.org', date: '2021-11', url: 'scrum.org/certificates/psm-i' },
  ],
  projects: [
    { name: 'E-commerce Platform', description: 'Developed a full-stack e-commerce platform with React, Node.js, and MongoDB', technologies: ['React', 'Node.js', 'MongoDB', 'Redux', 'Express'] },
    { name: 'Machine Learning Recommendation System', description: 'Built a recommendation engine using collaborative filtering and content-based approaches', technologies: ['Python', 'TensorFlow', 'Pandas', 'Flask'] },
  ],
  interests: ['Open-source contribution', 'Hiking', 'Chess', 'Reading tech blogs'],
};